### ISSUE TITLE
MSVC install order during Tsunami install

### ISSUE THREAD

**Issue by xifi-kif** [AdunanzA/Tsunami#1]
Ok, let me be the one starting with 1st issue.

The normal behavior should be:
- Installer checks if MSVC is already installed:
-- if it's already installed, install Tsunami
-- if it's not installed, install MSVC then install Tsunami

Instead it goes this way:
- Installer installs Tsunami and open it, and simultaneously it runs MSVC installer. And it runs MSVC installer whether it is already present or not.

**Comment by biuken** [comment]
This issue was moved to https://forum.adunanza.net/t/msvc-install-order-during-tsunami-install/14542
