### ISSUE TITLE
Impossible to resize columns in search window [0.6.3]

### ISSUE THREAD

**Issue by Sylstar** [AdunanzA/Tsunami#6]
As the title, from release 0.6.3, columns in search window were reduced and is impossible to resize them

Here is a screenshot about the issue:
![80bc1fb85257b4a8f35624483056bc1ff42bb339](https://user-images.githubusercontent.com/35277275/41509554-2f9976c2-7256-11e8-89a0-edd8c74fa250.jpg)

**Comment by gobne** [comment]
Thanks a lot :)

**Comment by gobne** [comment]
It has been solved
